modules/Projects/Routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::admin('projects', function () {
    Route::resource('projects', 'Projects', ['middleware' => ['dropzone']]);

    Route::get('/modal/tacks_statuses', 'Tasks@getStatuses')->name('projects.modals.tacks_statuses');
    Route::post('/modal/create_tacks_statuses', 'Tasks@createStatuses')->name('projects.modals.create_tacks_statuses');

    Route::group(['prefix' => 'projects/{project}'], function () {
        Route::resource('comments', 'Comments');
        Route::resource('tasks', 'Tasks');
        Route::resource('timesheets', 'Timesheets');
        Route::resource('milestones', 'Milestones');
        Route::resource('discussions', 'Discussions');
        // Route::resource('discussions/{discussion}/comments', 'Comments');

        // Route::resource('comments/{comment}/likes', 'DiscussionLikes');

        // Route::post('/transactions', function (\Modules\Projects\Models\Project $project) {
        //     $searchStringTransactions = $project->transactions()->collect();

        //     return view('projects::projects.show', compact('project', 'searchStringTransactions'));
        // })->name('transactions.index');

        // timesheet operations

        Route::post('tasks/{task}/status_update', 'Tasks@updateStatus')->name('tasks.status_update');
        Route::post('tasks/{task}/user/{user}/notify', 'Tasks@notify')->name('tasks.notify');

        Route::post('tasks/{task}/timesheets/start', 'Timesheets@start')->name('timesheets.start');
        Route::post('/timesheets/{timesheet}/stop', 'Timesheets@stop')->name('timesheets.stop');
        Route::post('discussions/{discussion}/like', 'Discussions@like')->name('discussions.like');
        Route::post('attachments', 'Projects@attachments')->name('attachment.store');
        Route::get('/invoice', 'Projects@invoice')->name('invoice');
        Route::post('/invoice', 'Projects@storeInvoice')->name('invoice.store');
    });

    // custom links
    Route::get('/projects/{project}/print', 'Projects@printProject')->name('projects.print');
    Route::get('/projects/discussions/{discussion}/comments', 'Discussions@comments')->name('discussions.comments');
    Route::get('/chart/profitloss/{project}', 'Projects@profitLoss');
    Route::get('/export/transactions/{project}', 'Projects@exportTransactions')->name('transactions.export');
    Route::get('/export/timesheets/{project}', 'Projects@exportTimesheets')->name('timesheets.export');
    Route::get('/projects/{project}/refresh', 'Projects@refresh')->name('projects.refresh');
    Route::get('/projects/{project}/refresh/tasks', 'Projects@refreshTasks')->name('tasks.refresh');
    Route::get('/projects/taskStatuses', 'Projects@getStatusTaks')->name('projects.taskStatuses');
    
});

modules/Projects/Models/Task.php
<?php

namespace Modules\Projects\Models;

use App\Abstracts\Model;
use App\Traits\Media;
use Illuminate\Database\Eloquent\Builder;

class Task extends Model
{
    use Media;

    protected $table = 'project_tasks';

    protected $dates = ['deleted_at', 'started_at', 'ended_at'];

    protected $fillable = ['company_id', 'project_id', 'milestone_id', 'name', 'description', 'status', 'started_at', 'deadline_at', 'priority', 'advance', 'billable', 'is_visible_to_customer', 'hourly_rate', 'created_by', 'is_invoiced', 'invoice_id'];

    public function milestone()
    {
        return $this->belongsTo('Modules\Projects\Models\Milestone');
    }

    public function project()
    {
        return $this->belongsTo('Modules\Projects\Models\Project');
    }

    public function users()
    {
        return $this->hasMany('Modules\Projects\Models\ProjectTaskUser', 'task_id')->where('is_liable', false);
    }

    public function liable()
    {
        return $this->hasMany('Modules\Projects\Models\ProjectTaskUser', 'task_id')->where('is_liable', true);
    }

    public function timesheets()
    {
        return $this->hasMany('Modules\Projects\Models\ProjectTaskTimesheet', 'task_id');
    }

    public function statusCurrent()
    {
        return $this->belongsTo('Modules\Projects\Models\TaskStatus', 'id', 'task_id');
    }

    public function statuses()
    {
        return $this->hasMany('Modules\Projects\Models\TaskStatuses', 'project_id', 'project_id');
    }

    public function statusById($id)
    {
        return $this->statuses->where('id', $id)->first();
    }

    public function comments()
    {
        return $this->hasMany('Modules\Projects\Models\Comment', 'task_id');
    }


    public function latestComment()
    {
        return $this->hasOne('Modules\Projects\Models\Comment', 'task_id')->latest();
    }

    public function scopeVisibleToCustomer(Builder $query)
    {
        return $query->where('is_visible_to_customer', true);
    }

    /**
     * Get the attachments.
     *
     * @return string
     */
    public function getAttachmentAttribute($value)
    {
        if (!empty($value) && !$this->hasMedia('attachment')) {
            return $value;
        } elseif (!$this->hasMedia('attachment')) {
            return false;
        }

        return $this->getMedia('attachment')->all();
    }

    public function getStatusColorAttribute()
    {
        return match ($this->status) {
            'not-started' => 'status-draft',
            'active' => 'status-partial',
            'completed' => 'status-success',
            default => 'status-draft',
        };
    }

    /**
     * Get the line actions.
     *
     * @return array
     */
    public function getLineActionsAttribute()
    {

        $projectTaskUser = ProjectTaskUser::where([
            'project_id' => $this->project_id,
            'milestone_id' => $this->milestone_id,
            'task_id' => $this->id,
            'user_id' => user_id(),
        ])->first();

        if (user()->isCustomer()) {
            return [
                [
                    'type' => 'button',
                    'title' => trans('general.show'),
                    'icon' => 'visibility',
                    'attributes' => [
                        '@click' => 'onModalAddNew("' . route('portal.projects.tasks.show', ['project' => $this->project->id, 'task' => $this->id]) . '")',
                    ],
                    'permission' => 'read-projects-portal-tasks',
                ]
            ];
        }

        $actions = [];

        if (user()->can('update-projects-tasks')) {
            $actions[] = [
                'type' => 'button',
                'title' => trans('general.edit'),
                'icon' => 'edit',
                'attributes' => [
                    '@click' => 'onModalAddNew("' . route('projects.tasks.edit', [$this->project->id, $this->id]) . '")',
                ],
                'permission' => 'update-projects-tasks',
            ];
        } else {
            $actions[] = [
                'type' => 'button',
                'title' => trans('general.show'),
                'icon' => 'visibility',
                'attributes' => [
                    '@click' => 'onModalAddNew("' . route('projects.tasks.show', ['project' => $this->project->id, 'task' => $this->id]) . '")',
                ],
                'permission' => 'read-projects-tasks',
            ];
        }

        $actions[] = [
            'type' => 'button',
            'title' => trans('general.notify'),
            'icon' => $projectTaskUser?->receive_notifications ? 'notifications' : 'notifications_off',
            'attributes' => [
                '@click' => 'onNotifyTask("' . route(
                    'projects.tasks.notify',
                    [
                        $this->project->id,
                        $this->id,
                        user_id()
                    ]
                ) . '")',
            ],
            'permission' => 'update-projects-tasks',
        ];

        $actions[] = [
            'type' => 'delete',
            'icon' => 'delete',
            'title' => trans_choice('projects::general.tasks', 1),
            'route' => [
                'projects.tasks.destroy',
                $this->project->id,
                $this->id,
            ],
            'permission' => 'delete-projects-tasks',
            'model' => $this,
        ];

        if ($this->timesheets->isEmpty() || $this->timesheets->last()->ended_at !== null) {
            $actions[] = [
                'type' => 'button',
                'title' => trans('general.start'),
                'icon' => 'play_arrow',
                'attributes' => [
                    '@click' => 'timesheet("' . route('projects.timesheets.start', [$this->project, $this]) . '")',
                ],
                'permission' => 'update-projects-timesheets',
            ];
        } elseif ($this->timesheets->isNotEmpty()) {
            $actions[] = [
                'type' => 'button',
                'title' => trans('projects::general.stop'),
                'icon' => 'stop',
                'attributes' => [
                    '@click' => 'timesheet("' . route('projects.timesheets.stop', [$this->project, $this->timesheets()->whereNull('ended_at')->first()]) . '")',
                ],
                'permission' => 'update-projects-timesheets',
            ];
        }

        $actions[] = [
            'type' => 'button',
            'title' => trans_choice('projects::general.comments', 0),
            'icon' => 'visibility',
            'attributes' => [
                '@click' => 'onModalAddNew("' . route('projects.comments.show',  [
                    'project' => $this->project->id,
                    'comment' => $this->id,
                    'task_id' => $this->id,
                    'type_comment' => 'task',
                ]) . '")',
            ],
            'permission' => 'update-projects-tasks',
        ];

        return $actions;
    }
}

modules/Projects/Resources/views/modals/invoice.blade.php
<x-form id="form-create-invoice" :route="['projects.invoice.store', $project->id]">
    <div class="grid sm:grid-cols-6 gap-x-8 gap-y-6 my-3.5">
        <x-form.group.select
            name="project_invoicing_type"
            :label="trans_choice('general.invoices', 1) . ' ' . trans('projects::general.info')"
            :options="$project_invoicing_type"
            form-group-class="sm:col-span-6"
        />

        <div class="sm:col-span-6">
            @foreach (['single_line', 'task_per_item', 'all_timesheets_individually'] as $name)
                <span class="mb-5" v-if="form.project_invoicing_type == '{{ $name }}'">{!! trans('projects::general.tooltips.' . $name) !!}</span>
            @endforeach
        </div>

        <div class="sm:col-span-6">
            {{ trans('projects::general.invoiced_tasks') }}
        </div>

        <div class="sm:col-span-6">
            <div class="text-red text-sm mt-1 block"
                v-if="form.errors.any() && Object.keys(form.errors.errors).some(function(k){ return ~k.indexOf('tasks') })">
                {{ trans('projects::validation.tasks_field') }}
            </div>

            <x-table>
                <x-table.thead>
                    <x-table.tr>
                        <x-table.th class="ltr:pr-6 rtl:pl-6" override="class">
                            <x-form.input.checkbox id="check_all" not-required @click="toggleAllCheckboxes($event)" />
                        </x-table.th>

                        <x-table.th class="w-4/12">
                            {{ trans('general.name') }}
                        </x-table.th>

                        <x-table.th class="w-4/12">
                            {{ trans_choice('general.statuses', 1) }}
                        </x-table.th>

                        <x-table.th class="w-4/12" kind="right">
                            {{ trans_choice('projects::general.priorities', 1) }}
                        </x-table.th>
                    </x-table.tr>
                </x-table.thead>

                <x-table.tbody>
                    @foreach($project->tasks as $item)
                        @continue($item->is_invoiced)
                        <x-table.tr>
                            <x-table.td class="ltr:pr-6 rtl:pl-6" override="class">
                                <x-form.input.checkbox selectable name="tasks[{{ $item->id }}]" value="false" not-required @click="toggleCheckboxes('tasks[{{ $item->id }}]')" />
                            </x-table.td>

                            <x-table.td class="w-4/12">
                                {{ $item->name }}
                            </x-table.td>

                            <x-table.td class="w-4/12">
                                <span class="flex items-center">
                                    <span class="px-2.5 py-1 text-xs font-medium rounded-xl bg-{{ $item->status_color }} text-text-{{ $item->status_color }}">
                                        {{ trans("projects::general.$item->status") }}
                                    </span>
                                </span>
                            </x-table.td>

                            <x-table.td class="w-4/12" kind="right">
                                @if($item->priority)
                                    {{ trans("projects::general.$item->priority") }}
                                @else
                                    <x-empty-data />
                                @endif
                            </x-table.td>
                        </x-table.tr>
                    @endforeach
                </x-table.tbody>
            </x-table>
        </div>
    </div>
</x-form>